# -*- encoding: utf-8 -*-
{
	'name': 'Reporte de Asiento de Destino',
	'category': 'account',
	'author': 'ITGRUPO-COMPATIBLE-BO',
	'depends': ['import_base_it','sh_message','automatic_fiscal_year_it'],
	'version': '1.0',
	'description':"""
	CREAR UN CAMPO DE TIPO LÓGICO EN LA TABLA ACCOUNT_ACCOUNT  PARA INDICAR QUE CUENTAS DEBEN TENER DESTINO,  SI ESTA MNARCADO ESTE CAMPO LA CUENTA SE MOSTRARÁ EN ELA VISTA 	
CREADA AUNQUE NO TENGA CUENTA ANALPITICA ASIGNADA  Y POR LO TANTO ESTOS TRES CAMPOS SE MOSTRARÁN VACIOS ( CTA : ANALITICA, AMARRE AL DEBE  Y AMARRE AL HABER ) 	
ANTES DE LA VISTA CREAR EL MENU ASIENTOS  AUTOMATICOS  EN DONDE ESTARÁ EL SUBMENU DE NOMBRE ANALISIS DE DESTINOS QUE PEDIRA PERIODO INICIAL Y PERIODO FINAL PARA EL QUE SE MUESTRE LOS DATOS 	
CREAR UNA VISTA EN DONDE PUEDE ANALIZARSE LA INFORMACIÓN DE LOS DESTINOS  POR CADA MOVIMIENTO CONTABLE,  PARA ESO SE USARÁ LA RELACIÓN QUE EXISTE ENTRE LA CUENTA ANALÍTICA Y EL CAMPO	
AMARRE AL DEBE CREADO EL FORMULARIO DE CUENTAS ANALÍTICAS.  Y PARA EL AMARRE AL HABER SE USARÁ LA CUENTA CONFIGURADA EN EL CAMPO DEL MISMO NOMBRE EN EL FORMULARIO  DE CREACIÓN  	
Y EDICIÓN DE CUENTAS CONTABLES 	
Name campo: Necesita Cuenta Analitica	
A CONTINUACIÓN SE MUESTRA EN LA FILA DE COLOR AMARILLO EL NOMBRE DEL CAMPO QUE TIENEN LAS TABLAS DE LA BASE DE DATOS ACCOUNT_MOVE Y ACCOUNT_MOVE_LINE 	
Y EL NOMBRE QUE TOMARÁ EN LA VISTA QUE SE ESTA REQUIRIENDO.	
	
CAMPO 	TABLA
	
PERIOD_ID	ACCOUNT_MOVE
DATE	ACCOUNT_MOVE
JOURNAL_ID	ACCOUNT_MOVE
PARTNER	ACCOUNT_MOVE_LINE
ref	AACOUNT_MOVE
ACCOUNT_ID	ACCOUNT_MOVE_LINE
DEBIT	ACCOUNT_MOVE_LINE
CREDIT	ACCOUNT_MOVE_LINE
analytic_account_id	ACCOUNT_MOVE_LINE
AMARRE_DEBE	CAMPO RELACIONADO
AMARRE_HABER	CAMPO RELACIONADO

	""",
	'auto_install': False,
	'demo': [],
	'data':	['wizard/account_account_analytic_rep_view.xml','wizard/account_account_analytic_wizard_view.xml','wizard/account_diario_moorage_view.xml'],
	'installable': True
}
