# -*- encoding: utf-8 -*-
{
	'name': 'Analisis de Vencimientos IT',
	'category': 'account',
	'author': 'ITGRUPO-COMPATIBLE-BO',
	'depends': ['import_base_it'],
	'version': '1.0',
	'description':"""
		1.- CREAR EL MENU ANALISIS VENCIMIENTOS ( VA DEBAJO DE CUENTAS CORRIENTES ) QUE ME MUESTRE UN WIZARD  COMO EL QUE ESTA ABAJO :						
						
FECHA INICIO : VALOR QUE INGRESA EL USUARIO , DESDE ESA FECHA SE EMPEZARA CALCULAR PARA VER LAS FACTURAS CUYA FECHA DE VENCIMIENTO CAE EN LOS SIGUIENTES INTERVALOS						
MENOS DE 15 						
NO DEBE CONSIDERARSE LAS FACTURAS QUE TENGAN FECHAS DE VENCIMIENTO MENOR A LA LA FECHA DE INICIO INTRODUCIDA 	DE 15 A 30	DE 31 A 45	DE 46 A 60	DE 61 A 90	DE 91 A 180	MAS DE 180
						
TIPO:   PARA ELEGIR SI ES CUENTAS POR COBRAR ( CUENTAS RECEIVABLES)  O ES CUENTAS POR PAGAR ( CUENTAS PAYABLES)						
EMPRESA: PARA SELECCIONAR LA EMPRESA , SI SE DEJA EN BLANCO TOMARÀ DE TODAS LA EMPRESAS						
CUENTA : PARA ELEGIR LA CUENTA ( SI SE ELIGIO RECEIVBALKE MUESTR SOLO LAS RECEIVABLES) SI SE ELIGE PAYABLE MUESTRA SOLO LAS PAYABLES), SI SE DEJA EN BLANCO MOSTRARA 						
PARA TODAS LAS CUENTAS DE ACURDO AL TIPO ELEGIDO ( RECEIVABLE O PAYABLE)						
FORMA DE REPORTE : MUESTRA UNA LISTA NO EDITABLE PARA ELEGIR ENTRE LAS SIGUIENTES OPCIONES ( EN COLUMNAS, EN COLUMNAS AGRUPADO , EN FILAS), * VER EXPLICACIÓN						
MOSTRAR EN : SE PODRA ELEGIR SI SE MUESTRA EN EXCEL O EN PANTALLA 						


	""",
	'auto_install': False,
	'demo': [],
	'data':	['wizard/account_contable_fch_wizard_view.xml'],
	'installable': True
}
