# -*- encoding: utf-8 -*-
{
    'name': 'Generador de asientos de destino',
    'category': 'account',
    'author': 'ITGRUPO-COMPATIBLE-BO',
    'depends': ['account_destino_it','import_base_it','sh_message'],
    'version': '1.0',
    'description':"""
    PERIODO:    ES EL PERIODO  DEL MOVIMIENTO CONTABLE REGISTRADO EN LA TABLA ACCOUNT_MOVE_LINE  "PERIOD_ID"                
LIBRO SUNAT:    ES EL TIPO DE PAGO CONFIGURADO EN EL DIARIO ( "nomlibro")  REGISTRADO EN LA TABLA ACCOUNT_MOVE              
VOUCHER :   ES EL CORRELATIVO DEL LIBRO SUNAT ("numopelibro") REGSTRADO EN LA TABLA ACOUNT_MOVE             
FECHA:  ES LA FECHA REGISTRADA EN LA TABLA ACCOUNT_MOVE             
TIPO:   ES EL TIPO DE PAGO CONFIGURADO EN EL JOURNAL_ID                 
"NUMERO 
COMPROBANTE: "  ES EL NÚMERO DE FACTURA DE PROVEEDOR QUE DIO ORIGEN AL MOVIMIENTO               
RUC:    ES EL RUC DEL PARTNER O PROVEEDOR PARA ESTE CASO A QUIEN SE LE COMPRO               
PROVEEDOR:  ES LA RAZON SOCIAL DEL PARTNER REGISTRADO EN  LA TABLA ACCOUNT_MOVE             
PRODUCTO:   ES EL PRODUCTO REGISTRADO EN CADA LINEA DE LA TABLA ACCOUNT_MOVE_LINE               
CUENTA FINANCIERA:  ES LA CUENTA USADA EN  CADA LÍNEA ( APUNTE CONTABLE) QUE CONTIENE ID DE PRODUCTOS               
DEBE:   EL MONTO CONSIGNADO EN EL DEBIT DEL APUNTE CONTABLE             
CREDIT: EL MONTO CONSIGNADO EN EL CREDIT DEL APUNTE CONTABLE                
CTA_VAR_EXISTENCIAS:    ES LA CUENTA CONTABLE CONFIGURADA EN EL CAMPO CUENTA DE ENTRADA DE EXISTENCIAS DE LA CATEGORIA DEL PRODUCTO             
CTA_ VALUACION: ES LA CUENTA CONTABLE CONFIGURADA EN EL CAMPO CUENTA DE VALORACION DE EXISTENCIAS DE LA CATEGORIA DEL PRODUCTO              

    """,
    'auto_install': False,
    'demo': [],
    'data': ['wizard/account_move_fch_wizard_view.xml',],
    'installable': True
}
