# -*- encoding: utf-8 -*-
{
	'name': 'Partner Name IT',
	'category': 'account',
	'author': 'ITGRUPO-COMPATIBLE-BO',
	'depends': ['import_base_it'],
	'version': '1.0',
	'description':"""

	CAMBIOS EN EL FORMULARIO DE PARTNER	
	
1	AGREGAR CAMPO TIPO DE DOCUMENTO  ANTES DE NOMBRE  EN ESTE CAMPO SE ELEGUIRA EL TIPO DE DOCUMENTO (  ESTA ENLAZADO A LA TABLA TIPO_DOC   QUE  TIENE
	LOS SIGUIENTES CAMPOS ( ID, CODIGO   CHAR(2) , DESCRIPCIÓN CHAR ( 70))
2	CUANDO SE  DSACTIVE EL CHECK ES EMPRESA MOSTRARÁ LOS CAMPOS  APE_PAT,  APE_MAT, NOMBRES EN LUGAR DEL CAMPO ÚNICO NOMBRE,  AHORA LA INFORMACIÓN SE GRABA EN EL 
	CAMPO NAME DE LA TABLA PARTNER CONCATENADO CONSIDERANDO LOS ESPACIOS EN BLANCO PARA SEPARAR NOMBRE Y CADA APELLIDO Y ADICIONALMENTE SE CREARA LOS CAMPOS 
	APE_PAT,  APE_MAT ,  NOMBRES EN DONDE SE GRABARA TAL CUELA INGHRESO EL USUARIO ESTOS DATOS.
	CUANDO SE TERMINE DE GRABAR LA INFORMACIÓN DEL NOMBRE  ESTE SE MOSTRARÁ COMO UN SOLO TEXTO,  AL EDITAR VUELVE A MOSTRAR LOS CAMPOS PARA PERSONAS NATURALES

	""",
	'auto_install': False,
	'demo': [],
	'data':	['res_partner_view.xml'],
	'installable': True
}
