# -*- encoding: utf-8 -*-
{
	'name': 'Res Currency Rate Change IT',
	'category': 'Currency',
	'author': 'ITGRUPO-COMPATIBLE-BO',
	'depends': ['base','account','account_invoice_it'],
	'version': '1.0.0',
	'description':"""
	UNA VEZ INSERTADO LOS CAMPOS LA  GRILLA MOSTRADA ARRIBA QUEDARÁ DE LA SIGUIENTE FORMA :  		
		
FECHA	TIPO COMPRA	TIPO VENTA 
01/01/2015	3,562	3,561
02/01/2015	3,546	3,542
03/01/2015	3,648	3,647
		
1.- INSTALAR EL MÓDULO  DECIMAL_PRECISION_CURRENCY		
2.- EL USUARIOINGRESARÁ MANUALMENTE LOS TIPOS DE COMPRA Y VENTA SUNAT		
3.- CADA VEZ QUE ACTUALICE EL TIPO DE CAMBIO VENTA LA TASA   SE ACTUALIZARA USANDO LA SIGUIENTE FÓRMULA  : 		
		
	TASA =   1/ TIPO DE CAMBIO VENTA 	
		
4.- AGREGAR EL TIPO DE CAMBIO VENTA QUE CORREPONDE A LOS FORMULARIOS DE FACTURAS DE PROVEEDORES, FACTURAS DE CLIENTES, FACTURAS RECTIFICATIVAS 		
Y ASIENTOS CONTABLES 		
		
EN LOS FORMULARIOS SE MOSTRARÁ EL TIPO DE CAMBIO DE ACUERDO A LA FECHA DE EMISIÓN DE LA FACTURA   DEBAJO DE L CAMPO DIVISA Y EN ASIENTOS CONTABLES SE GRABARÁ ESTE TIPO DE CAMBIO EN CADA UNA 		
DE LAS LÍNEAS GENERADAS POR LOS ASISTENTES EN UN CAMPO DENOMINADO T_CAMB   QUE ESTARÁ ANTES DE IMPORTE DIVISA  Y SERÁ DE TIPO EDITABLE.		
OJO NO GRABA NINGÚN ID SOLO GRABA UN NÚMERO QUE ES EL TIPO DE CAMBIO USADO EN EL ASISTENTE  PARA CREACIÓN DE FACTURAS 		
		
5.- CREAR UN CAMPO DENOMINADO TIPO DE CAMBIO PERSONALIZADO DEBAJO DEL CAMPO TIPO DE CAMBIO SUNAT ,  ES UN CUDARO DE TEXTO QUE PERMITE INGRESAR ESTE TIPO DE CAMBIO 		
Y QUE SERVIRÁ LUEGO PARA PODER USAR ESE TIPO DE CAMBIO EN LUGAR DEL TIPO DE CAMBIO SUNAT EN CADA UNO DE LSO ASISTENTE ( FACTURAS PROVEEDOR, FACTURA CLIENTES, FACTURA RECTIFICATIVAS) 		

	""",
	'auto_install': False,
	'demo': [],
	'data':	['res_currency_view.xml'],
	'installable': True
}
