# -*- encoding: utf-8 -*-
{
	'name': 'Reporte de Cuenta Contable IT',
	'category': 'account',
	'author': 'ITGRUPO-COMPATIBLE-BO',
	'depends': ['import_base_it','automatic_fiscal_year_it'],
	'version': '1.0',
	'description':"""
		1.-	AGREGAR FUNCIONALIDAD PARA QUE QUEDE SIEMPRE REGISTRADO EN CADA LINEA DE UN ASIENTO CONTABLE  DONDE ESTA LA CUENTA PAYABLE O RECEIVABLE QUE FACTURA ES LA QUE SE ESTA 										
	PAGANDO. SI ES NECESARIO QUE SE CREE UN NUEVO CAMPO , Y QUE SE  GRABE AHÍ EL ID  QUE IDENTINFICA AL DCUMENTO QUE SE ESTA PAGANDO , ES DECIR EL ID DONDE SE REGISTRO LA FACTURA 										
	EN EL ACCOUNT_MOVE.										
2.-	CREAR REPORTE DE CUENTAS CORRIENTES QUE MUESTRE LA INFORMACIÓN ORDENADA PRIMERO POR FECHA, LUEGO POR PROVEEDOR Y DESPUES POR FACTURA CONSIDERANDO LA 										
	PROVISIÓN DE LAFACTURA Y DEBAJO TODOS LOS PAGOS RELACIONADOS CON ESA FACTURA 										
											
3.-	PARA GENERAR ESTE REPORTE EN PANTALLA O EN PDF DEBE SOLICTAR LOS SIGUIENTES PARAMETROS : 										
											
	CUENTA CONTABLE:	ACA SE ELIGE LA CUENTA PARA LA QUE SE QUIERE MOSTRAR EL ESTADO DE CUENTA 									
	PARTNER:	ACA E ELIGE EL PARTNER ,  SI SE DEJA EN BLANCO MOSTRARÁ DE TODOS LOS PARTNERS									
	PERIODO INCIAL :	DESDE QUE PERIODO SE QUIERE MOSTRAR LOS APUNTES CONTABLES EN DONDE ESTE LA CUENTA SELECCIONADA ANTES									
	PERIODO FINAL: 	HASTA QUE PERIODO SE MOSTRARA LOS APUNTES CONTABLES DE LA CUENTA SELECCIONADA}									
											
4.-	EL LISTADO OBTENIDO DEBE PERMITIR AGRUPAR  Y  FILTRAR POR PARTNER, RUC, PERIODO Y DIARIO.  										
			5.-	SE EXPLICA DE DONDE SALE LA INFORMACIÓN DE CADA COLUMNA DEL REPORTE DE CUENTAS CORRIENTES							
								


	""",
	'auto_install': False,
	'demo': [],
	'data':	['wizard/account_contable_period_view.xml','wizard/account_contable_fch_wizard_view.xml'],
	'installable': True
}
